"""Remove start_time and end_time from Event model

Revision ID: 6a9942f6bc8a
Revises: de11d5c5d99a
Create Date: 2025-01-21 14:46:49.805645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9942f6bc8a'
down_revision = 'de11d5c5d99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=True))

    # ### end Alembic commands ###
