"""Add tags and category columns to Event model

Revision ID: 6fb7cef25434
Revises: d5a3eef223c7
Create Date: 2025-01-21 16:07:20.021887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb7cef25434'
down_revision = 'd5a3eef223c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('tags', sa.String(length=100), nullable=True))
    op.add_column('event', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'category')
    op.drop_column('event', 'tags')
    # ### end Alembic commands ###
