"""Initial migration

Revision ID: d59619f1ac93
Revises: f15965f9b4c3
Create Date: 2025-01-24 09:56:00.352279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59619f1ac93'
down_revision = 'f15965f9b4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
