"""Remove start_time and end_time from Event model

Revision ID: d5a3eef223c7
Revises: 6a9942f6bc8a
Create Date: 2025-01-21 15:31:32.492602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a3eef223c7'
down_revision = '6a9942f6bc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
