"""Add tags and category columns to Event model

Revision ID: f15965f9b4c3
Revises: 6fb7cef25434
Create Date: 2025-01-22 09:12:18.753177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15965f9b4c3'
down_revision = '6fb7cef25434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
